### PR TITLE
Refactored the codebase and fixed a major bug in LoadCanvasTemplateNoReload component

### PR DESCRIPTION
**Pull request by kumartul**
**Changes**

- Added a .gitignore file to ignore some of the files which are not meant to be shared
- Deleted serviceWorker.js and logo.svg
- Updated 'react' and 'react-dom'
- Used 'const' instead of 'let' wherever I could
- Used strict equality checks
- Removed some unused variables
- Used template literals instead of escaping the special characters
- Fixed a major bug in LoadCanvasTemplateNoReload component
- Updated the README
- Refactored the codebase a lot

### CODE REVIEW

**Comment by yadayadafahir** [comment]
Hello, masroorejaz! I saw @kumartul's tweet on Twitter that he had made some changes in your repository.
I reviewed the changes and I want to ask you why did you not merge the changes?
The changes were very good
He fixed one major bug
He made your README beautiful 
He used best practises and improved the logic

I recommend to merge the changes

**Comment by kumartul** [comment]
Thanks Ajay for supporting me! I don't know why @masroorejaz didn't merge my changes...

**Comment by masroorejaz** [comment]
I am super busy and have to review the changes myself so it will take some time. One more thing I know removing true from the code wasn't a big. I added it so even beginner level developer can easily understand it.

@kumartul kindly can you convert the npm so it can work with next.js as well? I am getting tons of requests for it.

Thank you.

**Comment by kumartul** [comment]
Thanks for reopening my request... Appreciate it!

**Comment by kumartul** [comment]
Thanks for reopening my request... Appreciate it!

**Comment by masroorejaz** [comment]
@kumartul  kindly can you convert the npm so it can work with next.js as well? I am getting tons of requests for it.

Thank you.

**Comment by masroorejaz** [comment]
I am closing it for now. Will review your changes in the future (as I am super busy now) and merge it if I find something worthwhile.

Thank you.

**Comment by kumartul** [comment]
No problem... 
I built my own library

No need to review the changes 

Thanks :)

**Pull request closed without merging**
