### PR TITLE
[FIX Spelling] Backwards compatible renaming

### PR DESCRIPTION
**Pull request by thomas-br**
@masroorejaz Adding onto the discussions from #13 / #8, can't we do a backwards compatible renaming?
 So correcting but keep exporting the misspelled variant?

### CODE REVIEW

**Comment by masroorejaz** [comment]
Thomas my buddy Thank you for your contribution but  problems will still remain. If somebody is using the current version and he/she will deploy it on somewhere and In case I merge your changes than all of the sudden the project will stop working due to spelling change.

Therefore closing without merging.

Thanks again and keep up the good work :)

Following you on Github!

**Comment by thomas-br** [comment]
@masroorejaz I don't think it will break as both spellings are being exported. The correction is backwards compatible. 

Existing consumers can continue using the wrong spelling, and at the same time you can use the corrected one.

**Comment by masroorejaz** [comment]
FIX Spelling  Backwards compatible renaming by thomas-br · Pull Request #22 · masroorejaz_react-sim
I maybe missing something here but in that case you need to create function with two spellings. The changes you have made only have function with one spelling. It will not be backward compatible in that case.

**Comment by thomas-br** [comment]
> I maybe missing something here but in that case you need to create function with two spellings. The changes you have made only have function with one spelling. It will not be backward compatible in that case.

The screenshot of yours is just the README, there I replace – correct.

But in the class itself, I exported both variants:

https://github.com/thomas-br/react-simple-captcha/blob/320ea40891d7e3425d66cbd05a119516a4f7b898/src/hooks/react-simple-captcha.js#L13

image

**Comment by masroorejaz** [comment]
Oh yeah didn't saw that.

I am kind of really busy right now. Will merge and release a new version once I have got free.

Thank you for your contribution.

**Comment by masroorejaz** [comment]
It's still causing bugs. 
Best to leave it that way.

**Pull request closed without merging**
